# -*- coding: utf-8 -*-
"""Gensim Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PSpxDblUn7Q_GH6hgisH_9uyHnDX2HuQ
"""

import gensim
import pandas as pd
import numpy as np

file =[]
for file_path in os.listdir("data/"):
    file = open("data/" + file_path, "r")
    for line in file:
        file.append(line+"\n")

df = pd.Series(file)
print(df.shape)
vocab_tokens = df.apply(gensim.utils.simple_preprocess)
model = gensim.models.Word2Vec(window = 5, min_count = 1, workers = 2)
model.build_vocab(vocab_tokens, progress_per = 1000)
model.train(vocab_tokens, total_examples=model.corpus_count, epochs = 10)

model.save("model_gensim_movies.model")

model.wv.most_similar("upset")